devices([
  "iPhone 17 Pro Max"
])

languages([
  "fr-FR"
])

scheme("PetitesNuitsScreenshots")

output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
override_status_bar(true)
launch_arguments(["-screenshot"])
xcodebuild_formatter("")
